/**
 * @file DriverCommands.h
 * @brief Represents the commands sent to the controller driver.
 *
 * DriverCommands contains the requested actuator values generated by the
 * controller logic and passed to the hardware abstraction layer.
 *
 */

#pragma once

struct DriverCommands
{
    /**
     * @brief Requested rudder position set point in degrees.
     *
     * The concrete driver implementation is responsible for converting this
     * value into the appropriate hardware command format.
     */
    double rudderSetPoint = 0.0;

    /**
     * @brief Requested throttle set point.
     *
     * The unit and valid range depend on the specific actuator and driver
     * implementation.
     */
    double throttleSetPoint = 0.0;
};